site_name: Learning Ghidra


nav:
    - Home: index.md
    - General Notes: general-notes.md
    - Tutorials:
      - First Tutorial: tutorials/first-tutorial/first-tutorial.md
      - Second Tutorial: tutorials/second-tutorial/second-tutorial.md

theme:
  name: 'material'
  custom_dir: 'theme'
  logo:
    icon: 'security'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  palette:
    primary: 'deep purple'
    accent: 'purple'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
      use_pygments: True
      noclasses: True
      pygments_style: monokai
      

extra_css:
  - stylesheets/extra.css
  # - stylesheets/dark_theme.css
  # - stylesheets/codehilite.css
